### ISSUE TITLE
incompatibilty with the subcaption package

### ISSUE THREAD

**Issue by ybagdasa** [UWIT-IAM/UWThesis#2]
Hello,

I was hoping to use the subcaption package so that I can use subfigures, but it seems that it is incompatible with the uwthesis class. In the preamble, I have the following referencing that package:

``  \usepackage{caption}
\usepackage{subcaption}``

but I get the following error when trying to compile 

``Package caption Warning: \caption will not be redefined since it's already
(caption)                redefined by a document class or package which is
(caption)                unknown to the caption package.
See the caption package documentation for explanation."

which means I cannot use the subcaption feature according to the caption package documentation. I can resort to minipage as I've been doing, but I'm curious whether there is a better way to go about nesting figures with their own captions.

Thanks
Y

**Comment by jimfox** [comment]
My immediate thought is to remove the caption part of the uwthesis class file.  I don't remember exactly why it's there, but I think to deal with multi-page captions, facing-page captions, and etc.  Possibly this package does all that you need.
Let me know.
Jim

________________________________________

**Comment by ybagdasa** [comment]
I've tried to comment out the section on captions in the uwthesis class file, but that did not solve the issue. I've resorted to using minipage. It is more cumbersome that subcaptioning, but works for now.  If compatible with uwthesis format standards, I do think subcaption package would be a good addition.

**Comment by ybagdasa** [comment]
Update: I realized that I was editting another uwthesis.cls file located in the same folder as my tex document, NOT the one being used located in the /usr/share/texmf/...   directory. Naturally the changes weren't being implemented. 

Commenting out the caption section of the class file indeed solved the problem. I can now use subcaption. 

Thanks
Y

**Comment by jimfox** [comment]
Glad you figured it out.
Jim

________________________________________
